Logic Commit : Major Refactor in code in LogicSearch.java
LogicSearch TDD - SUT  Error Found:
	
	Error: Junit test returned false instead of true
	
	Possible Source of error: 
		'TYPE_ALL' is not present in LogicSearch.java - startLetterSearch()